FROM brandonschabell/tensorflow-cuda:conda3.6

# RUN apt-get update && \
#	apt-get install -y \
#	libopenblas-base \
#	libomp-dev

COPY requirements.txt /tmp/requirements.txt
RUN source activate pyenv && \
	pip install -r /tmp/requirements.txt
